name: Cloud integration

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "macOS-13", "windows-2022"]
        python-version: ["3.10"]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 25
    env:
      TORCH_URL: "https://download.pytorch.org/whl/cpu/torch_stable.html"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install package & dependencies
        run: |
          pip --version
          pip install -e '.[test,extra]' -U -q --find-links $TORCH_URL
          pip list

      - name: Test integrations
        env:
          LIGHTNING_USER_ID: ${{ secrets.LIGHTNING_USER_ID }}
          LIGHTNING_API_KEY: ${{ secrets.LIGHTNING_API_KEY }}
        run: |
          coverage run --source litmodels -m pytest src tests -v -m cloud
        timeout-minutes: 15
