name: "Build (& deploy) Docs"
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set Python 3.10
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"
          activate-environment: true
          enable-cache: true

      - name: Install package & docs dependencies
        run: uv pip install -e '.[docs]'

      - name: Build docs
        env:
          SPHINX_MOCK_REQUIREMENTS: "0"
        run: python -m sphinx -b html -W --keep-going docs/source docs/build/html

      - name: Upload prepared docs
        uses: actions/upload-artifact@v7
        with:
          name: docs-html-${{ github.sha }}
          path: docs/build/html

  # https://github.com/marketplace/actions/deploy-to-github-pages
  docs-deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6 # deploy needs git credentials
      - name: Download prepared docs
        uses: actions/download-artifact@v8
        with:
          name: docs-html-${{ github.sha }}
          path: docs/build/html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        if: ${{ github.event_name == 'push' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/build/html # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs # If you'd like to push the contents of the deployment folder into a specific directory
          single-commit: true # you'd prefer to have a single commit on the deployment branch instead of full history
