name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/release-pypi.yml"
  release:
    types: [published]

# based on https://github.com/pypa/gh-action-pypi-publish

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install uv and set Python 3.10
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: "3.10"
          activate-environment: true
          enable-cache: true

      - name: Install dependencies
        run: |
          uv pip install -U '.[build]'
          uv pip list

      - name: Build package
        run: python -m build

      - name: Check package
        run: twine check dist/* --strict

      # We do this, since failures on test.pypi aren't that bad
      - name: Publish to Test PyPI
        if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository-url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
